#version 430
layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(rgba32f, binding = 0) uniform image3D noiseTexture;

//hash by Dave Hoskins
vec3 hash33(vec3 p3)
{
	p3 = fract(p3 * vec3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yxz+33.33);
    return fract((p3.xxy + p3.yxx)*p3.zyx);
}

float Worley(vec3 p, float scale){
    vec3 i = floor(p*scale);
    vec3 f = fract(p*scale);
    
    float min_dist = 10.;
    
    for (float z = -1.; z <= 1.; z++){
        for (float y = -1.; y <= 1.; y++){
            for (float x = -1.; x <= 1.; x++)
            {
                vec3 off = vec3(x, y, z);
                vec3 r = hash33(mod(i + off, scale)) + off - f;
                
                float d = dot(r, r);
            
                min_dist = min(min_dist, d);
            }
        }
    }
    return min_dist;
}

void main()
{
    ivec3 id = ivec3(gl_GlobalInvocationID.xyz);
    vec3 uvw = vec3(id) / (gl_NumWorkGroups * gl_WorkGroupSize);
    
    vec4 noises = vec4(0.);
    
    noises.r = 1.-Worley(uvw, 4.);
    noises.g = 1.-Worley(uvw, 8.);
    noises.b = 1.-Worley(uvw, 10.);
    
    imageStore(noiseTexture, id, noises);
}