#version 430
layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout(rgba32f, binding = 0) uniform image3D noiseTexture;

#define TWO_PI 6.28318530718


//hash by Dave Hoskins
float hash13(vec3 p3)
{
	p3  = fract(p3 * .1031);
    p3 += dot(p3, p3.zyx + 31.32);
    return fract((p3.x + p3.y) * p3.z);
}

vec3 hash33dir(vec3 p) 
{
    float off = hash13(p) * 1024.;

    float lon = hash13(p+off) * TWO_PI;
    float lat = hash13(p-off) * TWO_PI;

    float x = sin(lon) * cos(lat);
    float y = sin(lat);
    float z = cos(lon) * cos(lat);

    return vec3(x, y, z);
}

//hash by Dave Hoskins
vec3 hash33(vec3 p3)
{
	p3 = fract(p3 * vec3(.1031, .1030, .0973));
    p3 += dot(p3, p3.yxz+33.33);
    return fract((p3.xxy + p3.yxx)*p3.zyx);
}

float remap(float orig_val, float orig_min, float orig_max, float new_min, float new_max)
{
    return new_min + (((orig_val - orig_min) / (orig_max - orig_min)) * (new_max - new_min));
}

float Perlin(vec3 p, float scale)
{
    vec3 i = floor(p*scale);
    vec3 f = fract(p*scale);
    
    vec3 c000 = hash33dir(mod(i + vec3(0., 0., 0.), scale));
    vec3 c001 = hash33dir(mod(i + vec3(0., 0., 1.), scale));
    vec3 c010 = hash33dir(mod(i + vec3(0., 1., 0.), scale));
    vec3 c011 = hash33dir(mod(i + vec3(0., 1., 1.), scale));
    vec3 c100 = hash33dir(mod(i + vec3(1., 0., 0.), scale));
    vec3 c101 = hash33dir(mod(i + vec3(1., 0., 1.), scale));
    vec3 c110 = hash33dir(mod(i + vec3(1., 1., 0.), scale));
    vec3 c111 = hash33dir(mod(i + vec3(1., 1., 1.), scale));
    
    vec3 p000 = f - vec3(0., 0., 0.);
    vec3 p001 = f - vec3(0., 0., 1.);
    vec3 p010 = f - vec3(0., 1., 0.);
    vec3 p011 = f - vec3(0., 1., 1.);
    vec3 p100 = f - vec3(1., 0., 0.);
    vec3 p101 = f - vec3(1., 0., 1.);
    vec3 p110 = f - vec3(1., 1., 0.);
    vec3 p111 = f - vec3(1., 1., 1.);
    
    vec3 u = f*f*(3.0-2.0*f);
    
    float a = mix(dot(c000, p000), dot(c100, p100), u.x);
    float b = mix(dot(c001, p001), dot(c101, p101), u.x);
    float c = mix(dot(c010, p010), dot(c110, p110), u.x);
    float d = mix(dot(c011, p011), dot(c111, p111), u.x);

    float E = mix(a, c, u.y);
    float F = mix(b, d, u.y);
    
    return mix(E, F, u.z);
}

float Worley(vec3 p, float scale){
    vec3 i = floor(p*scale);
    vec3 f = fract(p*scale);
    
    float min_dist = 10.;
    
    for (float z = -1.; z <= 1.; z++){
        for (float y = -1.; y <= 1.; y++){
            for (float x = -1.; x <= 1.; x++)
            {
                vec3 off = vec3(x, y, z);
                vec3 r = hash33(mod(i + off, scale)) + off - f;
                
                float d = dot(r, r);
            
                min_dist = min(min_dist, d);
            }
        }
    }
    return min_dist;
}

float Worley_FBM(vec3 p, float scale){
    float o = 0.;
    float amp = 0.625;

    for (int i = 0; i < 2; i++){
        o += Worley(p, scale) * amp;
        scale *= 2.;
        amp *= 0.4;
    }
    return 1.-o;
}

float Perlin_FBM(vec3 p, float scale){
    float o = 0.;
    float amp = 0.5;
    
    for (int i = 0; i < 7; i++){
        o += Perlin(p, scale) * amp;
        scale *= 2.;
        amp *= 0.55;
    }
    return o;
}

float PerlinWorley(vec3 p, float scale){
    float perlin = Perlin(p, scale)*.5+.5;
    float worley = Worley_FBM(p, scale*2.);

    return remap(perlin, -worley, 1., 0., 1.);
}


void main()
{
    ivec3 id = ivec3(gl_GlobalInvocationID.xyz);
    vec3 uvw = vec3(id) / (gl_NumWorkGroups * gl_WorkGroupSize);
    
    vec4 noises = vec4(0.);
    
    noises.r = PerlinWorley(uvw, 5.);
    noises.g = Worley_FBM(uvw, 8.);
    noises.b = Worley_FBM(uvw, 16.);
    noises.a = Worley_FBM(uvw, 32.);
    

    imageStore(noiseTexture, id, noises);
}